    system("cls");
        cout << "#" << setfill('=') << setw(40) << "#" << endl;
        cout << "|" << setw(40) << left << "Data Mahasiswa" << "|" << endl;
        cout << "|" << setfill('=') << setw(40) << "|" << endl;
        cout << "|" << setw(40) << left << "1. Input Data Mahasiswa" << "|" << endl;
        cout << "|" << setw(40) << left << "2. Tampilkan Data Mahasiswa" << "|" << endl;
        cout << "|" << setw(40) << left << "0. Keluar" << "|" << endl;
        cout << "#" << setfill('=') << setw(40) << "#" << endl;
        cout << "Pilih Menu : ";
        cin >> pilih;
        cin.ignore();